//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WMSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WMSResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Common.WMSResource", typeof(WMSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_stock where materialid=&apos;#materialid&apos; limit 1.
        /// </summary>
        public static string checkmaterial {
            get {
                return ResourceManager.GetString("checkmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(availableqty ) as availableqty from wms.wms_stock where materialid=&apos;#materialid&apos;.
        /// </summary>
        public static string checkmaterialandqty {
            get {
                return ResourceManager.GetString("checkmaterialandqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.&quot;MaterialMasterYGS&quot; where material=&apos;#materialid&apos;.
        /// </summary>
        public static string checkmatexists {
            get {
                return ResourceManager.GetString("checkmatexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_stock where materialid=&apos;#materialid&apos; and createddate::date&lt;&apos;#createddate&apos;  order by createddate asc limit 1.
        /// </summary>
        public static string checkoldestmaterial {
            get {
                return ResourceManager.GetString("checkoldestmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct* from wms.wms_polist openpo
        ///        left join wms.wms_securityinward inw on openpo.pono=inw.pono 
        ///        left join wms.wms_pomaterials pomat on pomat.pono=openpo.pono
        ///         left join wms.wms_project pro on pro.pono=openpo.pono
        ///        where openpo.pono=&apos;#pono&apos;  
        ///        order by receiveddate desc limit 1.
        /// </summary>
        public static string checkponoexists {
            get {
                return ResourceManager.GetString("checkponoexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_stock where availableqty &gt;=#availableqty limit 1.
        /// </summary>
        public static string checkqty {
            get {
                return ResourceManager.GetString("checkqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_reprinthistory where .
        /// </summary>
        public static string checkreprintalreadydone {
            get {
                return ResourceManager.GetString("checkreprintalreadydone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepassmaterial set deleteflag=&apos;true&apos; where gatepassmaterialid=#gatepassmaterialid.
        /// </summary>
        public static string deletegatepassmaterial {
            get {
                return ResourceManager.GetString("deletegatepassmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from wms.testcrud where id = #id.
        /// </summary>
        public static string deletetestcurd {
            get {
                return ResourceManager.GetString("deletetestcurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ts.inwmasterid, ts.projectcode,ts.mrnremarks ,ts.grnnumber,emp.name as mrnby,ts.mrnon,
        ///prj.projectmanager
        ///from wms.wms_securityinward ts
        ///left outer join wms.employee emp on emp.employeeno = ts.mrnby
        ///left outer join wms.wms_project prj on prj.pono = ts.pono
        ///where ts.mrnby is not null and prj.projectmanager = &apos;#empno&apos;.
        /// </summary>
        public static string directtransfermainquery {
            get {
                return ResourceManager.GetString("directtransfermainquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select tsd.inwmasterid,tsd.materialid,tsd.confirmqty,mat.materialdescription
        ///from wms.wms_storeinward tsd
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = tsd.materialid
        ///where tsd.inwmasterid = &apos;#inw&apos;.
        /// </summary>
        public static string directtransfertr {
            get {
                return ResourceManager.GetString("directtransfertr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;meta charset=\&quot;ISO-8859-1\&quot;&gt;&lt;head&gt;&lt;link rel =&apos;stylesheet&apos; href =&apos;https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css&apos;&gt;&lt;/head&gt;
        ///&lt;body&gt;&lt;div class=&apos;container&apos;&gt;
        ///&lt;p&gt;Dear #user,&lt;/p&gt;
        ///&lt;p&gt;#subbody&lt;/p&gt;
        ///&lt;p&gt;
        ///LINK:&lt;/p&gt;
        ///&lt;a href=&quot;http://10.29.15.183:100/WMS/Login&quot;&gt;http://10.29.15.183:100/WMS/Login&lt;/a&gt;
        ///&lt;p style=&apos;margin-bottom:0px;&apos;&gt;Regards,&lt;/p&gt;&lt;p&gt; #sender.&lt;/p&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string emailbody {
            get {
                return ResourceManager.GetString("emailbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_rd_category where deleteflag=false.
        /// </summary>
        public static string getabccategorydata {
            get {
                return ResourceManager.GetString("getabccategorydata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.v_getdeailsbycategory  where category like &apos;%abcname&apos;.
        /// </summary>
        public static string GetABCdetailsBycategory {
            get {
                return ResourceManager.GetString("GetABCdetailsBycategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Sum(op.unitprice*ws.availableqty) as totalcost,
        ///    sum(availableqty) as availableqty,( SELECT wrc.categoryname
        ///           FROM wms.wms_rd_category wrc
        ///          WHERE op.unitprice ::numeric &gt;= wrc.minpricevalue::numeric and
        ///          (op.unitprice ::numeric &lt;= wrc.maxpricevalue::numeric or op.unitprice ::numeric = wrc.maxpricevalue::numeric is null) and wrc.deleteflag=false
        ///         LIMIT 1) AS category from wms.wms_stock ws
        /// inner join wms.&quot;MaterialMasterYGS&quot; op on  ws.materialid =op.material [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetallavlqtyABCList {
            get {
                return ResourceManager.GetString("GetallavlqtyABCList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select asno.pono, asno.asn,po.suppliername as vendorname,asno.deliverydate from wms.wms_asn asno left outer join wms.wms_polist po
        ///on asno.pono = po.pono.
        /// </summary>
        public static string getASNList {
            get {
                return ResourceManager.GetString("getASNList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select bin.binnumber,sk.binid,sk.materialid as material,sum(sk.availableqty)as availableqty,max(sk.itemlocation)as itemlocation
        /// from wms.wms_rd_bin bin left join wms.wms_stock sk  on bin.binid=sk.binid group by sk.binid,sk.materialid,bin.binnumber order by sk.binid asc.
        /// </summary>
        public static string getbinlist {
            get {
                return ResourceManager.GetString("getbinlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ws.unitprice,ws.materialid,op.materialdescription,
        ///    sum(availableqty) as availableqty,( SELECT wrc.categoryname
        ///           FROM wms.wms_rd_category wrc
        ///          WHERE ws.unitprice ::numeric &gt;= wrc.minpricevalue::numeric and 
        ///          ws.unitprice ::numeric &lt;= wrc.maxpricevalue::numeric  and wrc.deleteflag=false 
        ///         LIMIT 1) AS category from wms.wms_stock ws
        /// inner join wms.&quot;MaterialMasterYGS&quot; op on  ws.materialid =op.material 
        /// WHERE ws.materialid IS NOT null and ws.unitprice is not [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getcategorylist {
            get {
                return ResourceManager.GetString("getcategorylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select itemid, sec.grnnumber , totalquantity,availableqty,totalquantity - availableqty AS issuedqty,itemlocation from
        ///wms.wms_stock ws inner join wms.wms_securityinward sec on sec.pono =ws.pono where ws.materialid=&apos;#materialid&apos;.
        /// </summary>
        public static string getcategorylistbymaterailid {
            get {
                return ResourceManager.GetString("getcategorylistbymaterailid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stinw.inwardid,stinw.inwmasterid,stinw.materialid as material,secinw.grnnumber,secinw.pono,secinw.invoiceno,secinw.onhold,mat.materialdescription,stinw.receivedqty,stinw.receiveddate,stinw.returnqty,qc.qualitypassedqty,qc.qualityfailedqty,qc.remarks,qc.qcby as checkedby
        ///  from wms.wms_storeinward stinw
        ///  left outer join wms.wms_securityinward secinw on secinw.inwmasterid=stinw.inwmasterid
        ///  left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = stinw.materialid
        ///  left outer join wms.wms_qu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getdataforqualitydetails {
            get {
                return ResourceManager.GetString("getdataforqualitydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select orgdepartmentid as value, orgdepartment as text from wms.orgdepartments
        ///where boolinuse = True.
        /// </summary>
        public static string getdepartmentmasterdata {
            get {
                return ResourceManager.GetString("getdepartmentmasterdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select (select sum(issuedqty) from wms.wms_materialissue  where requestforissueid =req.requestforissueid  ) as issuedqty,max(iss.approvedstatus) as approvedstatus,max(pro.projectname)as projectname,max(req.requestforissueid)as requestforissueid,max(emp.&quot;name&quot;)as name,req.requesteddate,sk.materialid,
        ///req.requestedquantity,(select sum(availableqty) from wms.wms_stock ws where materialid =sk.materialid ) as availableqty,(select sum(reservedqty) from wms.wms_materialreserve wm where wm.materialid =sk.materiali [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetdetailsByrequestidWithoutPO {
            get {
                return ResourceManager.GetString("GetdetailsByrequestidWithoutPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select (select sum(issuedqty) from wms.wms_materialissue  where requestforissueid =req.requestforissueid  ) as issuedqty,max(iss.approvedstatus) as approvedstatus,max(pro.projectname)as projectname,max(req.requestforissueid)as requestforissueid,max(emp.&quot;name&quot;)as name,req.requesteddate,sk.materialid,max(sk.pono)as pono,
        ///req.requestedquantity,(select sum(availableqty) from wms.wms_stock ws where materialid =sk.materialid ) as availableqty,(select sum(reservedqty) from wms.wms_materialreserve wm where wm.mate [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetdetailsByrequestidWithPO {
            get {
                return ResourceManager.GetString("GetdetailsByrequestidWithPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select mat.pono,mat.materialid as material,ms.materialdescription,mat.materialqty,sinw.invoiceno,sinw.grnnumber,
        ///inw.inwardid,inw.qualitychecked,inw.returnedby,inw.returnedon,inw.returnremarks,inw.receivedqty,inw.returnremarks,
        ///qc.qualitypassedqty,qc.qualityfailedqty,qc.qcby as checkedby,
        /// CASE
        ///     WHEN inw.returnedby is null THEN qc.qualitypassedqty
        ///     ELSE  inw.confirmqty
        ///  END as confirmqty,
        ///CASE
        ///     WHEN inw.returnedby is null THEN qc.qualityfailedqty
        ///     ELSE  inw.returnqty
        ///  END as retu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Getdetailsforthreewaymatching {
            get {
                return ResourceManager.GetString("Getdetailsforthreewaymatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select itemid,createddate::date,materialid,mat.materialdescription,itemlocation,shelflife,sk.availableqty ,pono from wms.wms_stock sk inner join  wms.&quot;MaterialMasterYGS&quot; mat on mat.material=sk.materialid
        ///where stockstatus=&apos;active&apos; and sk.deleteflag=false and availableqty!=0.
        /// </summary>
        public static string getFIFOList {
            get {
                return ResourceManager.GetString("getFIFOList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM  wms.wms_gatepassapprovals where gatepassid =#gatepassid ORDER BY historyid DESC LIMIT 2.
        /// </summary>
        public static string getGatePassApprovalHistoryList {
            get {
                return ResourceManager.GetString("getGatePassApprovalHistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_gatepass gate 
        ///left join wms.employee emp on emp.employeeno=gate.requestedby  where approverid=&apos;#approverid&apos;.
        /// </summary>
        public static string getgatepassapproverdata {
            get {
                return ResourceManager.GetString("getgatepassapproverdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ygs.materialdescription,emp.name,iss.itemissueddate,gate.remarks as  statusremarks, * from wms.wms_gatepass gate
        ///   left join wms.wms_gatepassmaterial mat on gate.gatepassid=mat.gatepassid 
        ///   left join wms.employee emp on emp.employeeno=gate.requestedby
        ///   left join wms.wms_materialissue iss on iss.gatepassmaterialid = mat.gatepassmaterialid 
        ///   left join wms.&quot;MaterialMasterYGS&quot; ygs on ygs.material=mat.materialid and mat.deleteflag=false 
        ///   where gate.deleteflag=false   order by gate.gatepassi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getgatepasslist {
            get {
                return ResourceManager.GetString("getgatepasslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_gatepassmaterial material
        ///      inner join wms.wms_gatepass pass on pass.gatepassid=material.gatepassid 
        ///      inner join wms.employee emp on pass.requestedby=emp.employeeno
        ///      left join wms.&quot;MaterialMasterYGS&quot; ygs on ygs.material=material.materialid left join wms.wms_materialissue wissue on wissue.gatepassmaterialid  = material.gatepassmaterialid 
        ///      left join wms.wms_stock stock on stock.itemid  = wissue.itemid 
        ///           where pass.gatepassid=#gatepassid and pass.deletef [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getgatepassmaterialdetailList {
            get {
                return ResourceManager.GetString("getgatepassmaterialdetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk left join wms.&quot;MaterialMasterYGS&quot; ygs on ygs.material=sk.materialid.
        /// </summary>
        public static string getgatepassunitprice {
            get {
                return ResourceManager.GetString("getgatepassunitprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select MAX(stinw.inwardid) as value,sinw.grnnumber as text,(select suppliername from wms.wms_polist where pono = Max(sinw.pono) limit 1) as supplier 
        ///from wms.wms_storeinward stinw
        ///left outer join wms.wms_securityinward sinw on stinw.inwmasterid = sinw.inwmasterid 
        ///where (stinw.confirmqty is null or stinw.confirmqty = 0)  and sinw.grnnumber is not null and sinw.onhold is not True  group by stinw.inwmasterid,sinw.grnnumber.
        /// </summary>
        public static string getgrnlistdata {
            get {
                return ResourceManager.GetString("getgrnlistdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stinw.inwardid as value,sinw.grnnumber as text,
        ///(select suppliername from wms.wms_polist where pono = sinw.pono limit 1) as supplier
        ///from wms.wms_storeinward stinw 
        ///left outer join wms.wms_securityinward sinw on stinw.inwmasterid = sinw.inwmasterid 
        ///where stinw.returnedby is not null and sinw.isdirecttransferred is NOT True
        ///and stinw.inwardid not in (select distinct inwardid from wms.wms_stock where inwardid is not null order by inwardid desc).
        /// </summary>
        public static string getgrnlistdataforputaway {
            get {
                return ResourceManager.GetString("getgrnlistdataforputaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select grnnumber from wms.wms_securityinward   where pono=&apos;#pono&apos; and grnnumber is not null 
        ///and deleteflag=false order by grndate desc limit 1.
        /// </summary>
        public static string getGRNNo {
            get {
                return ResourceManager.GetString("getGRNNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sinw.inwmasterid,sinw.invoiceno,sinw.pono,sinw.onhold,sinw.onholdremarks,
        ///sinw.receiveddate,sinw.unholdedon,sinw.unholdremarks,emp1.name as unholdedby,
        ///inw.materialid as material,ms.materialdescription,inw.inwardid,inw.checkedby,
        ///inw.qualitychecked,inw.returnedby,inw.returnedon,inw.returnremarks,inw.receivedqty,
        ///(select suppliername from wms.wms_polist where pono = sinw.pono limit 1) as vendorname,
        ///inw.returnremarks,inw.materialqty,emp.name as receivedby from wms.wms_storeinward inw 
        ///left outer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getHoldGRdetail {
            get {
                return ResourceManager.GetString("getHoldGRdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sl.pono||&apos;-&apos;||sl.invoiceno as value,sl.pono||&apos;-&apos;||sl.invoiceno as text,(select suppliername from wms.wms_polist where pono = sl.pono limit 1) as supplier 
        ///from wms.wms_securityinward sl 
        ///where sl.onhold = True 
        ///order by sl.inwmasterid desc.
        /// </summary>
        public static string getHoldGRList {
            get {
                return ResourceManager.GetString("getHoldGRList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select emp.name,orgdept.departmenthead  as approverid,emp1.name as managername from wms.employee  emp
        /// inner join wms.orgdepartments orgdept on orgdept.orgdepartmentid=emp.orgdepartmentid
        /// inner join wms.employee emp1 on emp1.employeeno=orgdept.departmenthead
        /// where emp.employeeno=&apos;#employeeno&apos;.
        /// </summary>
        public static string getimmediatemnger {
            get {
                return ResourceManager.GetString("getimmediatemnger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select st.transferid,st.itemid,st.materialid,mat.materialdescription,st.previouslocation,st.previousqty,st.currentlocation,st.transferedqty,st.transferedon,emp.name as transferedby,st.remarks 
        ///from wms.wms_stocktransfer st 
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = st.materialid
        ///left outer join wms.employee emp on emp.employeeno = st.transferedby order by st.transferid desc.
        /// </summary>
        public static string getinternalstocktransferdata {
            get {
                return ResourceManager.GetString("getinternalstocktransferdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sinward.grnnumber,sinward.invoiceno, 
        ///      sum(storeinward .receivedqty) as receivedqty, sum(storeinward.returnqty) as returnedqty,
        ///      sum(storeinward.confirmqty) as confirmedqty from wms.wms_securityinward sinward
        ///left join wms.wms_storeinward storeinward on sinward.inwmasterid = storeinward.inwmasterid 
        ///where sinward.pono = &apos;#pono&apos; group by sinward.grnnumber,sinward.invoiceno.
        /// </summary>
        public static string getInvoiceDetails {
            get {
                return ResourceManager.GetString("getInvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(*) from wms.wms_securityinward  where pono =&apos;#pono&apos;  and invoiceno =&apos;#invno&apos;.
        /// </summary>
        public static string getinvoiceexists {
            get {
                return ResourceManager.GetString("getinvoiceexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inv.id,inv.transferid, inv.materialid , mat.materialdescription, inv.sourcelocation ,inv.sourceitemid, inv.destinationlocation, inv.destinationitemid,inv.transferqty
        ///from wms.wms_invtransfermaterial inv
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on inv.materialid = mat.material
        ///where inv.transferid = &apos;#tid&apos;.
        /// </summary>
        public static string getinvtransfermaterialdetail {
            get {
                return ResourceManager.GetString("getinvtransfermaterialdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inwmasterid from wms.wms_securityinward where grnnumber=&apos;#grnno&apos; limit 1.
        /// </summary>
        public static string getinwardidbygrn {
            get {
                return ResourceManager.GetString("getinwardidbygrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inwmasterid from wms.wms_securityinward where grnnumber=&apos;#grnnumber&apos; order by grndate desc limit 1.
        /// </summary>
        public static string getinwardmasterid {
            get {
                return ResourceManager.GetString("getinwardmasterid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inwmasterid from wms.wms_securityinward where pono=&apos;#pono&apos; and invoiceno=&apos;#invoiceno&apos; limit 1.
        /// </summary>
        public static string getinwmasterid {
            get {
                return ResourceManager.GetString("getinwmasterid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select itemid from wms.wms_stock where materialid=&apos;#materialid&apos; and pono=&apos;#pono&apos; limit 1.
        /// </summary>
        public static string getitemid {
            get {
                return ResourceManager.GetString("getitemid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_stock where materialid=&apos;#materialid&apos; .
        /// </summary>
        public static string getitemiddata {
            get {
                return ResourceManager.GetString("getitemiddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct sum(sk.availableqty)as availableqty,sk.pono,sk.materialid,sk.itemid,sk.itemlocation,ygs.materialdescription,ygs.material,createddate::DATE
        ///from wms.wms_stock sk inner join wms.&quot;MaterialMasterYGS&quot; ygs on ygs.material=sk.materialid where materialid=&apos;#materialid&apos;
        ///and availableqty&gt;0 --and sk.deleteflag=false
        ///group by sk.itemlocation,ygs.materialdescription,ygs.material,createddate::DATE,itemid.
        /// </summary>
        public static string getitemlocationList {
            get {
                return ResourceManager.GetString("getitemlocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  sum(sk.availableqty)as availableqty,(select sum(issuedqty) from wms.wms_materialissue wm where itemid =sk.itemid ) as issuedqty,sk.pono,sk.materialid,sk.itemid,sk.itemlocation,ygs.materialdescription,ygs.material,createddate::DATE
        ///from wms.wms_stock sk 
        ///inner join wms.&quot;MaterialMasterYGS&quot; ygs on ygs.material=sk.materialid 
        ///left join wms.wms_materialissue iss on iss.itemid =sk.itemid 
        ///where requestforissueid=&apos;#requestforissueid&apos; and
        ///sk.deleteflag=false
        ///group by sk.itemlocation,ygs.materialdescri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getitemlocationListBysIssueId {
            get {
                return ResourceManager.GetString("getitemlocationListBysIssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inwa.inwardid,bin.binnumber, rack.racknumber, loc.locatorname,mat.rackid,mat.binid,
        /// mat.storeid,stocks.itemlocation,stocks.availableqty,stocks.itemid,inw.grnnumber,inw.pono,inw.invoiceno,inw.receiveddate,
        /// inw.isdirecttransferred,inw.projectcode,emp.name as mrnby,inw.mrnon,inw.mrnremarks,
        /// inw.notifyremarks,inw.notifiedby,inw.notifiedtofinance,inw.notifiedon,inw.putawayfilename,
        /// inwa.materialqty,inwa.materialid as material,mat.materialdescription,inwa.receivedqty,inwa.confirmqty,inwa.returnqty  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getitemsfornotifypage {
            get {
                return ResourceManager.GetString("getitemsfornotifypage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_returnmaterial returnmat
        ///   where returnmat.returnid=#returnid .
        /// </summary>
        public static string getlistforconfirm {
            get {
                return ResourceManager.GetString("getlistforconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select issue.approvedstatus,req.pono,req.requestid,req.requesteddate,req.requesterid,emp.&quot;name&quot;,max(req.requesttype)as requesttype,max(req.returnon)as returnon
        ///        from wms.wms_materialrequest req 
        ///       left join wms.employee emp on req.requesterid=emp.employeeno 
        ///       --left join wms.wms_pomaterials pomat on pomat.pono=po.pono
        ///       --left join wms.wms_project pro on pro.pono=po.pono
        ///       left join wms.wms_materialissue issue on issue.requestforissueid=req.requestforissueid
        ///        --where [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetListForMaterialRequestByapproverid {
            get {
                return ResourceManager.GetString("GetListForMaterialRequestByapproverid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_materialrequest where requesterid=&apos;#requesterid&apos;.
        /// </summary>
        public static string GetListForMaterialRequestByrequesterid {
            get {
                return ResourceManager.GetString("GetListForMaterialRequestByrequesterid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_stock  stock 
        ///left join wms.wms_rd_bin bins on bins.binid=stock.binid
        ///left join wms.wms_rd_rack rack on rack.rackid=stock.rackid
        ///where itemid=#itemid.
        /// </summary>
        public static string getlocationasresponse {
            get {
                return ResourceManager.GetString("getlocationasresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  sk.itemlocation ,sk.materialid, sk.availableqty
        /// from wms.wms_securityinward sec 
        /// left join wms.wms_stock sk on sec.inwmasterid = sk.inwmasterid
        ///left join wms.&quot;MaterialMasterYGS&quot;  mtmaster on mtmaster.material= sk.materialid
        ///where sec.grnnumber =&apos;#grn&apos; and sk.materialid =&apos;#materialid&apos; and sk.availableqty!=0.
        /// </summary>
        public static string getLocationDetails {
            get {
                return ResourceManager.GetString("getLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Materialdescription from wms.&quot;MaterialMasterYGS&quot;  where Material = &apos;#materialid&apos;.
        /// </summary>
        public static string getMateDescr {
            get {
                return ResourceManager.GetString("getMateDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select max(sk.pono) as pono ,sk.materialid as material,Max(prj.projectmanager) as projectmanager,
        ///( select sum(availableqty) from wms.wms_stock ws where materialid =sk.materialid) as availableqty,
        ///max(mtmtr.unitprice) as materialcost,max(mtmtr.materialdescription) as materialdescription from wms.wms_stock  sk 
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mtmtr on mtmtr.material = sk.materialid
        ///left outer join wms.wms_project prj on prj.pono = sk.pono 
        ///where sk.availableqty &gt; 0 and (prj.projectmanager = &apos;#ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getmaterialdetailfprrequest {
            get {
                return ResourceManager.GetString("getmaterialdetailfprrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select mat.quantity as quantity,sum(req.requestedquantity)as requestedquantity,sum(res.reservedqty)as reservedqty,matiss.issuedqty as qtyissued,sec.grnnumber,openpo.material as materialid, (select sum(availableqty) from wms.wms_stock ws where materialid =sk.materialid) as qtyavailable,max(sk.totalquantity ) as qtytotal from wms.wms_stock sk left  join wms.wms_materialissue matiss on matiss.itemid=sk.itemid left join wms.wms_materialreserve res on res.itemid=sk.itemid left join wms.wms_securityinward sec on  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getMaterialDetails {
            get {
                return ResourceManager.GetString("getMaterialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct max(res.reserveformaterialid) as reserveformaterialid, max(sk.availableqty)as availableqty,res.pono,max(res.materialid)as materialid,max(res.reserveid) as reserveid,
        /// max(pro.jobname)as jobname,max(res.reservedon)as reservedon,max(res.reservedqty)as reservedqty,max(emp.&quot;name&quot;)as name 
        /// from wms.wms_materialreserve res
        ///inner join wms.employee emp on emp.employeeno=res.reservedby
        ///inner join wms.wms_stock sk on sk.pono=res.pono 
        ///left join wms.wms_polist op on op.pono=res.pono
        ///left join wm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getmaterialdetailsbyreserveid {
            get {
                return ResourceManager.GetString("getmaterialdetailsbyreserveid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select gtm.materialid as value,Max(mat.materialdescription) as text from wms.wms_materialissue mi
        ///left outer join wms.wms_materialrequest gtm on gtm.requestforissueid = mi.requestforissueid
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = gtm.materialid
        ///where mi.requestforissueid is not null and gtm.requesterid = &apos;#requestor&apos;
        ///group by gtm.materialid.
        /// </summary>
        public static string getmaterialfortransfer {
            get {
                return ResourceManager.GetString("getmaterialfortransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &apos;&apos; as jobname, inw.confirmqty,sec.grnnumber,sec.pono,mtmaster.materialdescription,
        ///sk.materialid, sk.availableqty,sk.itemid
        /// from wms.wms_securityinward sec left join wms.wms_storeinward inw on inw.inwmasterid=sec.inwmasterid
        ///left join wms.wms_stock sk on sec.inwmasterid = sk.inwmasterid
        ///left  join wms.wms_polist openpo on sk.pono = openpo.pono
        ///left join wms.&quot;MaterialMasterYGS&quot;  mtmaster on mtmaster.material= sk.materialid 
        ///where sec.grnnumber =&apos;#grnnumber&apos; and sk.materialid=&apos;#materialid&apos;.
        /// </summary>
        public static string getMaterialRequestDetails {
            get {
                return ResourceManager.GetString("getMaterialRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ts.transferid, ts.projectcode,ts.remarks as transferremarks,emp.name as transferedby,ts.createdon as transferredon
        ///from wms.wms_transfermaterial ts
        ///left outer join wms.employee emp on emp.employeeno = ts.createdby.
        /// </summary>
        public static string getMaterialTransferDetails {
            get {
                return ResourceManager.GetString("getMaterialTransferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  sec.inwmasterid,inw.confirmqty,sec.grnnumber,sec.pono,mtmaster.materialdescription,inw.materialid,sk.itemid
        /// from wms.wms_securityinward sec 
        /// left join wms.wms_stock sk on sec.inwmasterid = sk.inwmasterid
        ///left join wms.wms_storeinward inw on inw.inwmasterid=sec.inwmasterid
        ///left  join wms.wms_polist openpo on sk.pono = openpo.pono
        ///left join wms.&quot;MaterialMasterYGS&quot;  mtmaster on mtmaster.material= sk.materialid
        ///where sec.grnnumber =&apos;#grn&apos;.
        /// </summary>
        public static string getmatforgrnno {
            get {
                return ResourceManager.GetString("getmatforgrnno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sk.materialid,sk.itemlocation,sk.itemid, sk.returnid,sk.availableqty,mat.storeid as defaultstore,mat.rackid as defaultrack,mat.binid as defaultbin, * from wms.wms_returnmaterial rm
        ///left outer join wms.wms_stock sk on rm.returnid = sk.returnid
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = rm.materialid
        ///where rm.matreturnid=@matreid.
        /// </summary>
        public static string getmatreturndetails {
            get {
                return ResourceManager.GetString("getmatreturndetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Max(pono) as POno  from wms.wms_polist where pono like &apos;NP%&apos;.
        /// </summary>
        public static string getmaxnonpo {
            get {
                return ResourceManager.GetString("getmaxnonpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select requestid from wms.wms_materialrequest order by requestid desc limit 1.
        /// </summary>
        public static string getnextrequestid {
            get {
                return ResourceManager.GetString("getnextrequestid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select reserveid from wms.wms_materialreserve order by reserveid desc limit 1.
        /// </summary>
        public static string getnextreservetid {
            get {
                return ResourceManager.GetString("getnextreservetid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select matis.gatepassmaterialid,matis.itemid,matis.itemissueddate,ygs.materialdescription,emp.name,
        ///matgt.gatepassid,matgt.materialid,matgt.materialcost,matgt.quantity,
        ///gt.gatepasstype,gt.vendorname,gt.requestedby,gt.requestedon,emp3.name as mgapprover,emp4.name as fmapprover,
        ///matgt.outwarddate,emp1.name as outwardedby,matgt.outwardremarks,matgt.outwardqty,matgt.inwardqty,matgt.inwarddate,emp2.name as inwardedby,matgt.inwardremarks
        ///from wms.wms_materialissue matis
        ///left outer join wms.wms_gatepassmateri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getnonreturnablegatepassdata {
            get {
                return ResourceManager.GetString("getnonreturnablegatepassdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stk.inwmasterid,sinw.grnnumber,sinw.pono,sinw.invoiceno,(select suppliername from wms.wms_polist where pono = Max(sinw.pono) limit 1) as vendorname,
        ///Max(sinw.notifyremarks) as notifyremarks,Max(emp.name) as notifiedby,sinw.notifiedtofinance,Max(sinw.notifiedon) as notifiedon,Max(sinw.putawayfilename) as putawayfilename
        ///from wms.wms_stock stk
        ///left outer join wms.wms_securityinward sinw on stk.inwmasterid = sinw.inwmasterid 
        ///left outer join wms.employee emp on emp.employeeno=sinw.notifiedby
        ///where  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getnotifiedgrbydate {
            get {
                return ResourceManager.GetString("getnotifiedgrbydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stk.inwmasterid,sinw.grnnumber,sinw.pono,sinw.invoiceno,(select suppliername from wms.wms_polist where pono = Max(sinw.pono) limit 1) as vendorname,
        ///Max(sinw.notifyremarks) as notifyremarks,Max(emp.name) as notifiedby,sinw.notifiedtofinance,Max(sinw.notifiedon) as notifiedon,Max(sinw.putawayfilename) as putawayfilename
        ///from wms.wms_stock stk
        ///left outer join wms.wms_securityinward sinw on stk.inwmasterid = sinw.inwmasterid 
        ///left outer join wms.employee emp on emp.employeeno=sinw.notifiedby
        ///where  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getnotifiedgrnlist {
            get {
                return ResourceManager.GetString("getnotifiedgrnlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select matreturnid from wms.wms_returnmaterial order by matreturnid desc limit 1.
        /// </summary>
        public static string getnxtreturnid {
            get {
                return ResourceManager.GetString("getnxtreturnid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sl.pono||&apos;-&apos;||sl.invoiceno as value,sl.pono||&apos;-&apos;||sl.invoiceno as text,(select suppliername from wms.wms_polist where pono = sl.pono limit 1) as supplier 
        ///from wms.wms_securityinward sl 
        ///where sl.grnnumber is null and sl.onhold is NOT True and (sl.holdgrstatus is NULL or sl.holdgrstatus =  &apos;accepted&apos;)
        ///order by sl.inwmasterid desc.
        /// </summary>
        public static string getpendingreceiptslist {
            get {
                return ResourceManager.GetString("getpendingreceiptslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sk.pono, polist.suppliername,prj.projectmanager from wms.wms_stock sk
        ///left outer join wms.wms_polist polist on sk.pono = polist.pono
        ///left outer join wms.wms_project prj on sk.pono = prj.pono 
        ///where availableqty &gt;0  and prj.projectmanager = &apos;#manager&apos;
        ///group by sk.pono, polist.suppliername,prj.projectmanager.
        /// </summary>
        public static string getPODetails {
            get {
                return ResourceManager.GetString("getPODetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select pl.pono,sum(pomat.materialqty) as qty from wms.wms_polist pl
        ///join wms.wms_pomaterials pomat on pl.pono= pomat.pono 
        ///group by pl.pono.
        /// </summary>
        public static string getpolist {
            get {
                return ResourceManager.GetString("getpolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct* from wms.wms_storeinward inw inner join wms.wms_securityinward inwmaster on inwmaster.inwmasterid=inw.inwmasterid  
        ///where  inwmaster.pono=&apos;#pono&apos;.
        /// </summary>
        public static string Getponodetailsformaterialissue {
            get {
                return ResourceManager.GetString("Getponodetailsformaterialissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_gatepass where gatepassid=#gatepassid and deleteflag=false.
        /// </summary>
        public static string getprintdetails {
            get {
                return ResourceManager.GetString("getprintdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select projectcode as value, projectname as text from wms.wms_projectMaster.
        /// </summary>
        public static string getprojectlist {
            get {
                return ResourceManager.GetString("getprojectlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct grnnumber as value,pono as text,supplier,receiveddate::date from 
        ///(select stinw.inwardid,stinw.inwmasterid,stinw.materialid as material,
        /// secinw.grnnumber,secinw.onhold,mat.materialdescription,stinw.receivedqty,
        /// stinw.receiveddate,stinw.returnqty,qc.qualitypassedqty,qc.qualityfailedqty,
        /// qc.remarks,qc.qcby as checkedby,
        ///secinw.pono,(select suppliername from wms.wms_polist where pono = secinw.pono limit 1) as supplier
        ///  from wms.wms_storeinward stinw
        ///  left outer join wms.wms_security [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getqcdropdownbydate {
            get {
                return ResourceManager.GetString("getqcdropdownbydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct grnnumber as value,pono as text,supplier,receiveddate::date from 
        ///(select stinw.inwardid,stinw.inwmasterid,stinw.materialid as material,
        /// secinw.grnnumber,secinw.onhold,mat.materialdescription,stinw.receivedqty,
        /// stinw.receiveddate,stinw.returnqty,qc.qualitypassedqty,qc.qualityfailedqty,
        /// qc.remarks,qc.qcby as checkedby,
        ///secinw.pono,(select suppliername from wms.wms_polist where pono = secinw.pono limit 1) as supplier
        ///  from wms.wms_storeinward stinw
        ///  left outer join wms.wms_security [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getqualitycheckdropdown {
            get {
                return ResourceManager.GetString("getqualitycheckdropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select req.reserveid,max(req.reservedon)as reservedon,req.reservedby,po.projectname,emp.&quot;name&quot; 
        /// from wms.wms_materialreserve req left join wms.openpolistview po on po.pono=req.pono 
        ///left join wms.employee emp on req.reservedby=emp.employeeno 
        ///group by req.reserveid,req.reservedby,po.projectname,emp.&quot;name&quot; order by req.reserveid desc.
        /// </summary>
        public static string GetreleasedmaterialList {
            get {
                return ResourceManager.GetString("GetreleasedmaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(req.reservedqty)as reservedqty, req.materialid,Max(mat.materialdescription) as materialdescription,req.reserveid 
        ///from wms.wms_materialreserve  req
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material=req.materialid
        ///where req.reserveid=#reserveid and req.reservedqty&gt;0 
        ///group by req.reserveid,req.materialid.
        /// </summary>
        public static string Getreleasedqty {
            get {
                return ResourceManager.GetString("Getreleasedqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string getreportforcategory {
            get {
                return ResourceManager.GetString("getreportforcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select requestforissueid  from wms.wms_materialrequest where materialid=&apos;materialid&apos; and pono=&apos;#pono&apos; limit 1.
        /// </summary>
        public static string getrequestforissueid {
            get {
                return ResourceManager.GetString("getrequestforissueid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  max(&apos;&apos;)as projectname,max(res.reserveupto)as reserveupto,res.reserveid,max(res.pono) as pono,max(res.reservedon) as reservedon,
        ///max(iss.approvedstatus)as approvedstatus,max(emp.name)as requestedby,max(res.requestedon)as requestedon,
        ///CASE
        ///     WHEN max(res.reserveupto::date) &lt; current_date THEN
        ///	 &apos;Expired&apos;
        ///     WHEN max(res.requestedby) is NOT NULL THEN
        ///	  &apos;Requested&apos;
        ///	 ELSE &apos;Reserved&apos;
        ///  END as chkstatus
        ///from wms.wms_materialreserve res 
        ///left join wms.wms_stock sk on sk.materialid=res.mater [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getreservedmaterialList {
            get {
                return ResourceManager.GetString("getreservedmaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.wms_materialreserve reser
        ///inner join wms.employee emp on emp.employeeno=reser.reservedby
        ///where reserveupto between current_date and current_date  + interval &apos;3 day&apos; and releasedon is null.
        /// </summary>
        public static string Getreservelist {
            get {
                return ResourceManager.GetString("Getreservelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct max(retmat.matreturnid) as matreturnid,max(retmat.returnid ) as returnid, 
        ///  max(retmat.materialid) as materialid,max(retmat.returnqty) as returnqty,max(retmat.createdby) as createdby,max(retmat.createdon) as createdon
        ///  from wms.wms_returnmaterial retmat 
        ///  where retmat.createdby=&apos;#createdby&apos;
        ///  group by retmat.matreturnid.
        /// </summary>
        public static string getreturndata {
            get {
                return ResourceManager.GetString("getreturndata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select matreturnid,materialid,createdby ,
        ///  createdon, max(emp.&quot;name&quot;) as name, confirmstatus from wms.wms_returnmaterial reqtrasnfer 
        ///  left join wms.employee emp on emp.employeeno=reqtrasnfer.createdby
        ///  group by reqtrasnfer.returnid.
        /// </summary>
        public static string GetreturnList {
            get {
                return ResourceManager.GetString("GetreturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select mmy.material, mmy.materialdescription,sum(st.availableqty) as availableqty,mmy.safteystock as safteystock ,mmy.minorderqty as minorderqty
        ///from wms.&quot;MaterialMasterYGS&quot; mmy  join wms.wms_stock st on st.materialid =mmy.material where st.availableqty &lt; mmy.safteystock group by mmy.material.
        /// </summary>
        public static string getSafteyStockList {
            get {
                return ResourceManager.GetString("getSafteyStockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sl.pono,emp.name as receivedby,sl.asnno as asn,sl.invoiceno,
        ///(select suppliername from wms.wms_polist where pono = sl.pono limit 1) as suppliername
        ///from wms.wms_securityinward sl 
        ///left outer join wms.employee emp on sl.receivedby = emp.employeeno.
        /// </summary>
        public static string getsecurityreceivedlist {
            get {
                return ResourceManager.GetString("getsecurityreceivedlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select polist.pono, pomat.materialid as modelno, pomat.materialdescription as description,proj.jobname as jobname,
        /// pomat.materialqty as qty, pomat.itemdeliverydate as date from wms.wms_polist polist 
        /// join wms.wms_pomaterials pomat on pomat.pono = polist.pono join wms.wms_project proj on proj.pono =polist .pono 
        /// where polist.pono =&apos;#pono&apos; and pomat.materialid =&apos;#materialid&apos;.
        /// </summary>
        public static string GetStockDetails {
            get {
                return ResourceManager.GetString("GetStockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stocktype from wms.stocklocation where locationid=&apos;#locationid&apos; and location=&apos;#locationname&apos; and storeid=#stid and rackid=#rkid and binid=#biid limit 1.
        /// </summary>
        public static string getstocktype {
            get {
                return ResourceManager.GetString("getstocktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ts.transferid, ts.projectcode,ts.remarks as transferremarks,emp.name as transferedby,ts.createdon as transferredon
        ///from wms.wms_transfermaterial ts
        ///left outer join wms.employee emp on emp.employeeno = ts.createdby
        ///where ts.createdby=&apos;#createdby&apos;.
        /// </summary>
        public static string gettransferdata {
            get {
                return ResourceManager.GetString("gettransferdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select tsd.transferid,tsd.materialid,tsd.transferqty as transferredqty,mat.materialdescription
        ///from wms.wms_transfermaterialdetail tsd
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on mat.material = tsd.materialid
        ///where tsd.transferid = &apos;#tid&apos;.
        /// </summary>
        public static string gettransferiddetail {
            get {
                return ResourceManager.GetString("gettransferiddetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from wms.v_getAccessList where employeeid=&apos;#employeeid&apos; and roleid =#roleid.
        /// </summary>
        public static string getUserAcessNames {
            get {
                return ResourceManager.GetString("getUserAcessNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct rl.roleid,rm.rolename as accessname from wms.v_getAccessList rl
        ///left outer join wms.rolemaster rm on rl.roleid = rm.roleid
        ///where rl.employeeid = &apos;#employeeid&apos;.
        /// </summary>
        public static string getuserroles {
            get {
                return ResourceManager.GetString("getuserroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stk.inwmasterid,sinw.grnnumber,sinw.pono,sinw.invoiceno,(select suppliername from wms.wms_polist where pono = Max(sinw.pono) limit 1) as vendorname,
        ///Max(sinw.notifyremarks) as notifyremarks,Max(sinw.notifiedby) as notifiedby,sinw.notifiedtofinance,Max(sinw.notifiedon) as notifiedon,Max(sinw.putawayfilename) as putawayfilename
        ///from wms.wms_stock stk
        ///left outer join wms.wms_securityinward sinw on stk.inwmasterid = sinw.inwmasterid 
        ///where stk.inwmasterid is not NULL and sinw.notifiedtofinance is NOT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string grnlistfornotify {
            get {
                return ResourceManager.GetString("grnlistfornotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_rd_category(categoryid,categoryname,minpricevalue,maxpricevalue,createdby,createdon,deleteflag,startdate,enddate)values(default,@categoryname,@minpricevalue,@maxpricevalue,@createdby,current_date,false,@startdate,@enddate).
        /// </summary>
        public static string insertABCrange {
            get {
                return ResourceManager.GetString("insertABCrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.auth_users(authid,employeeid,roleid,createddate,createdby,deleteflag)values(default,@employeeid,@roleid,@createddate,@createdby,@deleteflag)returning authid.
        /// </summary>
        public static string insertAuthUserData {
            get {
                return ResourceManager.GetString("insertAuthUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_barcode(barcodeid,barcode,createddate,createdby,deleteflag)VALUES(DEFAULT,@barcode,@createddate,@createdby,@deleteflag)returning barcodeid.
        /// </summary>
        public static string insertbarcodedata {
            get {
                return ResourceManager.GetString("insertbarcodedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_fifoitemdistribution(fifoid,itemid,materialid,enteredon,pono)values(default,@itemid,@materialid,current_date,@pono).
        /// </summary>
        public static string insertFIFOdata {
            get {
                return ResourceManager.GetString("insertFIFOdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_storeinward(inwmasterid,receiveddate,receivedby,receivedqty,returnqty,qualitypassedqty,confirmqty,materialid,deleteflag,@onhold)
        ///VALUES(@inwmasterid,@receiveddate,@receivedby,@receivedqty,@returnqty,@qualitypassedqty,@confirmqty,@materialid,@deleteflag,@onhold)returning inwardid.
        /// </summary>
        public static string insertforinvoicequery {
            get {
                return ResourceManager.GetString("insertforinvoicequery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_gatepassapprovals(historyid,gatepassid,approverid,approvername,approverstatus,&quot;label&quot;,approvedon)values(default,@gatepassid,@approverid,@approvername,@approverstatus,@label,current_timestamp).
        /// </summary>
        public static string insertgatepassapprovalhistory {
            get {
                return ResourceManager.GetString("insertgatepassapprovalhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_gatepass(gatepassid, gatepasstype, status, referenceno, vehicleno, requestedby, requestedon,deleteflag,vendorname,print,reasonforgatepass,approverid,fmapproverid,fmapprovedstatus,approverstatus,remarks)values(default,@gatepasstype,@status,@referenceno,@vehicleno, @requestedby,@requestedon,@deleteflag,@vendorname,&apos;true&apos;,@reasonforgatepass,@approverid,@fmapproverid,@fmapprovedstatus,@approverstatus,@remarks)returning gatepassid.
        /// </summary>
        public static string insertgatepassdata {
            get {
                return ResourceManager.GetString("insertgatepassdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_gatepassmaterial(gatepassmaterialid,gatepassid,materialid,quantity,deleteflag,remarks,materialcost,expecteddate,issuedqty)
        ///values(default,@gatepassid,@materialid,@quantity,@deleteflag,@remarks,@materialcost,@expecteddate,@issuedqty).
        /// </summary>
        public static string insertgatepassmaterial {
            get {
                return ResourceManager.GetString("insertgatepassmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_securityinward(inwmasterid,pono,invoiceno,invoicedate,receivedby,receiveddate,deleteflag,departmentid,suppliername,asnno,inwardremarks,filename)VALUES(default,@pono,@invoiceno,@invoicedate,@receivedby,@receiveddate,@deleteflag,@departmentid,@suppliername,@asnno,@inwardremarks,@filename).
        /// </summary>
        public static string insertinvoicedata {
            get {
                return ResourceManager.GetString("insertinvoicedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_invstocktransfer (transferid,transferredby,transferredon,transfertype,sourceplant,destinationplant,remarks)
        ///values (@transferid,@transferredby,@transferredon,@transfertype,@sourceplant,@destinationplant,@remarks).
        /// </summary>
        public static string insertInvStocktransfer {
            get {
                return ResourceManager.GetString("insertInvStocktransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_invtransfermaterial (transferid,materialid,sourcelocation,sourceitemid,destinationlocation,destinationitemid,transferqty)
        ///values (@transferid,@materialid,@sourcelocation,@sourceitemid,@destinationlocation,@destinationitemid,@transferqty).
        /// </summary>
        public static string insertinvtransfermaterial {
            get {
                return ResourceManager.GetString("insertinvtransfermaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_polist(pono,suppliername,type) values (@pono,@suppliername,@type).
        /// </summary>
        public static string insertpo {
            get {
                return ResourceManager.GetString("insertpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  wms.wms_storeinward set  qualitypassedqty=@qualitypassedqty,qualityfailedqty = @qualityfailedqty,checkedby = @receivedby,checkedon=current_date,remarks=@remarks where inwardid =#inwardid.
        /// </summary>
        public static string insertqualitycheck {
            get {
                return ResourceManager.GetString("insertqualitycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_storageallowcationhistorymaster(itemlocation,itemid,createddate,createdby)values(@itemlocation,@itemid,@createddate,@createdby).
        /// </summary>
        public static string insertqueryforlocationhistory {
            get {
                return ResourceManager.GetString("insertqueryforlocationhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_qualitycheck(inwardid,quality,qtype,qcdate,qcby,remarks,deleteflag)VALUES(@inwardid,@quality,@qtype,@qcdate,@qcby,@remarks,@deleteflag).
        /// </summary>
        public static string insertqueryforqualitycheck {
            get {
                return ResourceManager.GetString("insertqueryforqualitycheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_trackstatus(pono,status,enteredon,returnqty)VALUES(@pono,&apos;Store Checked&apos;,current_timestamp,@returnqty).
        /// </summary>
        public static string insertqueryforstatusforqty {
            get {
                return ResourceManager.GetString("insertqueryforstatusforqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_trackstatus(pono,status,enteredon)VALUES(@pono,&apos;In Store&apos;,current_timestamp).
        /// </summary>
        public static string insertqueryforstatuswarehouse {
            get {
                return ResourceManager.GetString("insertqueryforstatuswarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_reprinthistory(reprinthistoryid,gatepassid,reprintedon,reprintedby,reprintcount)values(default,@gatepassid,current_date,@reprintedby,@reprintcount)returning reprinthistoryid.
        /// </summary>
        public static string insertreprintcount {
            get {
                return ResourceManager.GetString("insertreprintcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_materialreserve(reserveformaterialid,materialid,itemid,pono,reservedon,reservedby,reservedqty,reserveid,reserveupto)
        ///values(default,@materialid,@itemid,@pono,current_timestamp,@reservedby,@reservedqty,@reserveid,@reserveupto).
        /// </summary>
        public static string insertreservematerial {
            get {
                return ResourceManager.GetString("insertreservematerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  wms.wms_storeinward set  confirmqty=@confirmqty,returnqty = @returnqty,returnedby = @receivedby,returnedon=current_date,returnremarks=@returnremarks where inwardid =#inwardid.
        /// </summary>
        public static string insertreturndata {
            get {
                return ResourceManager.GetString("insertreturndata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_reprinthistory(reprinthistoryid,inwmasterid, reprintedon,reprintedby,reprintcount,barcodeid )values(default,@inwmasterid,current_date,@reprintedby,@reprintcount,@barcodeid)returning reprinthistoryid.
        /// </summary>
        public static string insertSecurityPrintHistory {
            get {
                return ResourceManager.GetString("insertSecurityPrintHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_stock(inwmasterid,stockstatus,pono,binid,rackid ,storeid, vendorid,totalquantity,shelflife,availableqty,deleteflag,itemlocation,createddate,createdby,materialid,inwardid)VALUES(@inwmasterid,@stockstatus,@pono,@binid,@rackid,@storeid,@vendorid,@totalquantity,@shelflife,@availableqty,@deleteflag,@itemlocation,@createddate,@createdby,@materialid,@inwardid)returning itemid.
        /// </summary>
        public static string insertstock {
            get {
                return ResourceManager.GetString("insertstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_transfermaterialdetail(transferid,materialid,transferqty)values
        ///        (@transferid,@materialid,@transferredqty).
        /// </summary>
        public static string inserttransfermaterials {
            get {
                return ResourceManager.GetString("inserttransfermaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inv.transferid,emp.name as transferredby,inv.transferredon,inv.transfertype,inv.sourceplant,inv.destinationplant,inv.remarks  
        ///from wms.wms_invstocktransfer inv 
        ///left outer join wms.employee emp  on emp.employeeno = inv.transferredby
        ///order by transferredon Desc.
        /// </summary>
        public static string invstocktransfermainquery {
            get {
                return ResourceManager.GetString("invstocktransfermainquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select grnnumber,onhold,unholdedby from wms.wms_securityinward where grnnumber = &apos;#grnno&apos;.
        /// </summary>
        public static string isgrnexistsbygrn {
            get {
                return ResourceManager.GetString("isgrnexistsbygrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select grnnumber,onhold,unholdedby from wms.wms_securityinward where pono = &apos;#pono&apos; and invoiceno = &apos;#invno&apos;.
        /// </summary>
        public static string isgrnexistsquerybyinvoce {
            get {
                return ResourceManager.GetString("isgrnexistsquerybyinvoce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select max(iss.materialissueid)as materialissueid,max(sk.itemid)as itemid,max(req.returnqty)as returnqty,max(sk.itemlocation)as itemlocation, max(iss.approvedstatus)as approvedstatus,max(req.requestedquantity)as requestedquantity, max(req.materialid)as materialid,max(mat.materialdescription) as materialdescription, max(req.requestid)as requestid,req.requestforissueid,sum(issuedqty)as issuedquantity
        /// from wms.wms_materialrequest  req
        /// left join wms.wms_materialissue iss on req.requestforissueid=iss.request [rest of string was truncated]&quot;;.
        /// </summary>
        public static string issuedqtydetails {
            get {
                return ResourceManager.GetString("issuedqtydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from  wms.wms_sequencemaster  where  enddate&gt;=current_date and id=1.
        /// </summary>
        public static string lastinsertedgrn {
            get {
                return ResourceManager.GetString("lastinsertedgrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_materialrequest(requestforissueid,quantity,approveremailid,approverid,pono,materialid,requesterid,requestid,requestedquantity,requesteddate,deleteflag)VALUES(default,@quantity,@approveremailid,@approverid,@pono,@materialid,@requesterid,@requestid,@requestedquantity,current_date,false).
        /// </summary>
        public static string materialquest {
            get {
                return ResourceManager.GetString("materialquest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct  max(req.ackstatus)as ackstatus,max(issue.issuedqty)as issuedquantity,max(req.requesteddate)as requesteddate,max(issue.approvedstatus)as approvedstatus,max(issue.issuedqty) as issuedqty,max(req.requestforissueid)as requestforissueid,max(issue.approvedstatus) as approvedstatus,req.requestid,max(openpo.pono) as pono,max(openpo.projectname)as projectname,max(openpo.material)as material,max(openpo.materialdescription) as materialdescription,max(openpo.quotationqty) quotationqty,max(req.requested [rest of string was truncated]&quot;;.
        /// </summary>
        public static string materialrequestquery {
            get {
                return ResourceManager.GetString("materialrequestquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  max(track.enteredon) as enteredon,max(pr.projectcode)as projectcode,max(wp.pono) as pono,min(track.status)as status,max(wp.suppliername )as vendorname,max(pr.jobname) as jobname,  (select  SUM(materialqty) from wms.wms_pomaterials where pono =wp.pono )  as materialqty, (select SUM(confirmqty) from wms.wms_storeinward where inwmasterid in (select inwmasterid from wms.wms_securityinward where pono = wp.pono)) as receivedqty from wms.wms_polist wp left join wms.wms_trackstatus track on track.pono=wp.po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string openpolist {
            get {
                return ResourceManager.GetString("openpolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.testcrud (name,ismanager) values (@name, @ismanager).
        /// </summary>
        public static string posttestcrud {
            get {
                return ResourceManager.GetString("posttestcrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set print=false,printedon=current_date,printedby=@printedby where gatepassid=#gatepassid.
        /// </summary>
        public static string printstatusupdate {
            get {
                return ResourceManager.GetString("printstatusupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.testcrud set name = @name,ismanager= @ismanager where id = #id.
        /// </summary>
        public static string puttestcurd {
            get {
                return ResourceManager.GetString("puttestcurd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inwa.inwardid,bin.binnumber, rack.racknumber, loc.locatorname,mat.rackid,mat.binid,
        /// mat.storeid,stocks.itemlocation,stocks.availableqty,stocks.itemid,inw.grnnumber,inw.pono,inw.invoiceno,inw.receiveddate,
        /// inw.isdirecttransferred,inw.projectcode,emp.name as mrnby,inw.mrnon,inw.mrnremarks,
        /// inwa.materialqty,inwa.materialid as material,mat.materialdescription,inwa.receivedqty,inwa.confirmqty,inwa.returnqty 
        /// from wms.wms_securityinward inw
        ///left join wms.wms_storeinward inwa on inw.inwmasterid=inw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string queryforitemdetails {
            get {
                return ResourceManager.GetString("queryforitemdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_storeinward(inwmasterid,receiveddate,receivedby,receivedqty,materialid,deleteflag,qualitycheckrequired,qualitychecked,materialqty,remarks)
        ///VALUES(@inwmasterid,@receiveddate,@receivedby,@receivedqty,@materialid,@deleteflag,@qualitycheck,@qualitychecked,@materialqty,@receiveremarks)returning inwardid.
        /// </summary>
        public static string receiveforinvoice {
            get {
                return ResourceManager.GetString("receiveforinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sinw.invoiceno,sinw.pono,sinw.grnnumber,sinw.onhold,sinw.onholdremarks,sinw.unholdedby,inw.remarks as receiveremarks,inw.materialid as material,ms.materialdescription,
        /// inw.inwardid,inw.qualitychecked,inw.returnedby,inw.returnedon,inw.returnremarks,inw.receivedqty,inw.returnremarks,inw.materialqty,
        /// qc.qualitypassedqty,qc.qualityfailedqty,qc.qcby as checkedby,
        /// CASE
        ///     WHEN inw.qualitycheckrequired != True and inw.returnedby is null THEN inw.receivedqty
        ///	 WHEN inw.qualitycheckrequired = True a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string receivequeryfornonpo {
            get {
                return ResourceManager.GetString("receivequeryfornonpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct openpo.projectname,inwa.invoiceno,inw.checkedby,inwa.grnnumber,inwa.pono,inw.qualitychecked,
        ///openpo.material,openpo.materialqty,inw.receivedqty,inw.returnedby,inw.returnedon,inw.returnremarks,
        ///openpo.materialdescription, openpo.quotationqty,inw.receivedqty,inw.returnqty,qc.qualitypassedqty,qc.qualityfailedqty,
        ///CASE
        ///     WHEN inw.returnedby is null THEN qc.qualitypassedqty
        ///     ELSE  inw.confirmqty
        ///  END as confirmqty,
        ///  CASE
        ///     WHEN inw.returnedby is null THEN qc.qualityfailedqty
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string receivequeryforpo {
            get {
                return ResourceManager.GetString("receivequeryforpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set reprintedon=current_date,reprintedby=@reprintedby,reprintcount=@reprintcount where gatepassid=#gatepassid.
        /// </summary>
        public static string reprintcountupdate {
            get {
                return ResourceManager.GetString("reprintcountupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_qualitycheck(inwardid,qualitypassedqty,qualityfailedqty,qcby,remarks,qcdate)
        ///  VALUES(@inwardid,@qualitypassedqty,@qualityfailedqty,@receivedby,@remarks,current_date).
        /// </summary>
        public static string savequalityquery {
            get {
                return ResourceManager.GetString("savequalityquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO wms.wms_trackstatus(pono,status,enteredon)VALUES(@pono,&apos;Security Checked&apos;,current_timestamp).
        /// </summary>
        public static string statusupdatebySecurity {
            get {
                return ResourceManager.GetString("statusupdatebySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select st.materialid,Max(mat.materialdescription) as materialdescription,SUM(st.transferedqty) transferedqty,st.transferedon from wms.wms_stocktransfer st
        ///left outer join wms.&quot;MaterialMasterYGS&quot; mat on st.materialid = mat.material
        ///group by st.materialid,st.transferedon order by st.transferedon desc.
        /// </summary>
        public static string Stocktransferbygroup {
            get {
                return ResourceManager.GetString("Stocktransferbygroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_stocktransfer (itemid,materialid,previouslocation,previousqty,currentlocation,transferedqty,transferedon,transferedby,remarks)
        ///values (@itemid,@materialid,@previouslocation,@previousqty,@currentlocation,@transferedqty,@transferedon,@transferedby,@remarks).
        /// </summary>
        public static string stocktransferinternal {
            get {
                return ResourceManager.GetString("stocktransferinternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string string1 {
            get {
                return ResourceManager.GetString("string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,name,ismanager from wms.testcrud.
        /// </summary>
        public static string testcrudget {
            get {
                return ResourceManager.GetString("testcrudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_rd_category set deleteflag=true,updatedby=@updatedby,updatedon=@updatedon  where categoryid=#categoryid.
        /// </summary>
        public static string updateABCrange {
            get {
                return ResourceManager.GetString("updateABCrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_materialrequest set ackstatus=@ackstatus,ackremarks=@ackremarks where requestid=@requestid.
        /// </summary>
        public static string updateackstatus {
            get {
                return ResourceManager.GetString("updateackstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_materialreserve set ackstatus=@ackstatus,ackremarks=@ackremarks where reserveid=@reserveid.
        /// </summary>
        public static string updateackstatusforreserved {
            get {
                return ResourceManager.GetString("updateackstatusforreserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set fmapprovedstatus=&apos;#fmapprovedstatus&apos;,fmapproverremarks=@fmapproverremarks,fmapprovedon=current_timestamp where gatepassid=@gatepassid.
        /// </summary>
        public static string updateApprovedstatusbyFMmanager {
            get {
                return ResourceManager.GetString("updateApprovedstatusbyFMmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set approverstatus=&apos;#approverstatus&apos;,approverremarks=@approverremarks,approvedon=current_timestamp where gatepassid=@gatepassid.
        /// </summary>
        public static string updateApprovedstatusbymanager {
            get {
                return ResourceManager.GetString("updateApprovedstatusbymanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_materialissue(materialissueid,pono,itemid,requestforissueid,itemissueddate,itemreceiverid,deleteflag,itemreturnable,approvedby,approvedon,issuedqty,approvedstatus)
        ///values(default,@pono,@itemid,@requestforissueid,@itemissueddate,@itemreceiverid,false,@itemreturnable,@approvedby,@approvedon,@issuedqty,@approvedstatus).
        /// </summary>
        public static string updateapproverstatus {
            get {
                return ResourceManager.GetString("updateapproverstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_materialissue(materialissueid,pono,itemid,reserveformaterialid,itemissueddate,itemreceiverid,deleteflag,itemreturnable,approvedby,approvedon,issuedqty,approvedstatus)
        /// values(default,@pono,@itemid,@reserveformaterialid,@itemissueddate,@itemreceiverid,false,@itemreturnable,@approvedby,@approvedon,@issuedqty,@approvedstatus).
        /// </summary>
        public static string updateapproverstatusforrelease {
            get {
                return ResourceManager.GetString("updateapproverstatusforrelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.cyclecountconfig set apercentage=@apercentage,bpercentage=@bpercentage,cpercentage=@cpercentage,cyclecount=@cyclecount,frequency=@frequency where id = #cid.
        /// </summary>
        public static string updatecyclecountconfig {
            get {
                return ResourceManager.GetString("updatecyclecountconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_materialreserve set releasedon=current_timestamp where reserveformaterialid=@reserveformaterialid.
        /// </summary>
        public static string updatedon {
            get {
                return ResourceManager.GetString("updatedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set gatepasstype=@gatepasstype,status=@status,referenceno=@referenceno,vehicleno=@vehicleno,requestedby=@requestedby,vendorname=@vendorname,reasonforgatepass=@reasonforgatepass,remarks=@remarks  where gatepassid=#gatepassid.
        /// </summary>
        public static string updategatepass {
            get {
                return ResourceManager.GetString("updategatepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepass set  status=@status, approverstatus=@approverstatus,approverremarks=@approverremarks,approvedon=@approvedon where gatepassid=#gatepassid.
        /// </summary>
        public static string updategatepassapproverstatus {
            get {
                return ResourceManager.GetString("updategatepassapproverstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_gatepassapprovals(historyid,gatepassid,fmapproverid,fmapprovername,fmapproverstatus,&quot;label&quot;)
        ///values(default,@gatepassid,@fmapproverid,@fmapprovername,&apos;Pending&apos;,@label).
        /// </summary>
        public static string updategatepasshistoryfornonreturn {
            get {
                return ResourceManager.GetString("updategatepasshistoryfornonreturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_gatepassmaterial set gatepassid=@gatepassid,materialid=@materialid,quantity=@quantity,remarks=@remarks,materialcost=@materialcost,expecteddate=@expecteddate,returneddate=@returneddate where gatepassmaterialid=#gatepassmaterialid.
        /// </summary>
        public static string updategatepassmaterial {
            get {
                return ResourceManager.GetString("updategatepassmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_materialissue(materialissueid,pono,itemid,gatepassmaterialid,itemissueddate,itemreceiverid,deleteflag,itemreturnable,approvedby,approvedon,issuedqty,approvedstatus)
        ///values(default,@pono,@itemid,@gatepassmaterialid,@itemissueddate,@itemreceiverid,false,@itemreturnable,@approvedby,@approvedon,@issuedqty,@approvedstatus).
        /// </summary>
        public static string updategatepassmaterialissue {
            get {
                return ResourceManager.GetString("updategatepassmaterialissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_securityinward set grnnumber=@grnnumber,grndate=current_date where invoiceno=&apos;#invoiceno&apos; and pono=&apos;#pono&apos;.
        /// </summary>
        public static string updategrnnumber {
            get {
                return ResourceManager.GetString("updategrnnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set itemlocation=&apos;#itemlocation&apos; ,binid=@binid,rackid=@rackid where itemid=#itemid.
        /// </summary>
        public static string updatelocation {
            get {
                return ResourceManager.GetString("updatelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set availableqty=(availableqty-#issuedqty) where itemid=#itemid.
        /// </summary>
        public static string updateqtyafterissue {
            get {
                return ResourceManager.GetString("updateqtyafterissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_storeinward set receiveddate=@receiveddate,receivedby=@receivedby,
        ///receivedqty=@receivedqty,qualitycheckrequired=@qualitycheck,qualitychecked=@qualitychecked,remarks=@receiveremarks
        ///where inwardid = &apos;#inwardid&apos;.
        /// </summary>
        public static string updatereceiptunhold {
            get {
                return ResourceManager.GetString("updatereceiptunhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_reprinthistory
        ///          set reprintcount=@reprintcount where reprinthistoryid=#reprinthistoryid.
        /// </summary>
        public static string updatereprintcount {
            get {
                return ResourceManager.GetString("updatereprintcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set availableqty=availableqty+@availableqty where itemid=@itemid.
        /// </summary>
        public static string updatereturnmaterialToStock {
            get {
                return ResourceManager.GetString("updatereturnmaterialToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_returnmaterial(returnid,returnqty,createdby,createdon,remarks,materialid,matreturnid)values
        ///  (default,@returnqty,@createdby,current_timestamp,@remarks,@materialid,@matreturnid).
        /// </summary>
        public static string UpdateReturnqty {
            get {
                return ResourceManager.GetString("UpdateReturnqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_returnmaterial set confirmstatus=&apos;Accepted&apos; where returnid=@returnid.
        /// </summary>
        public static string updatereturnqtyByInvMngr {
            get {
                return ResourceManager.GetString("updatereturnqtyByInvMngr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_sequencemaster set sequencenumber=@grnnextsequence where id=@id.
        /// </summary>
        public static string updateseqnumber {
            get {
                return ResourceManager.GetString("updateseqnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set availableqty=#availableqty where itemid=#itemid.
        /// </summary>
        public static string updatestock {
            get {
                return ResourceManager.GetString("updatestock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set availableqty=#availableqty where itemid=#itemid.
        /// </summary>
        public static string updatestockavailable {
            get {
                return ResourceManager.GetString("updatestockavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_stock(itemid,materialid,itemlocation,availableqty,createddate,createdby,returnid)values(default,@materialid,@itemlocation,@availableqty,current_timestamp,@createdby,@returnid).
        /// </summary>
        public static string updatetostockbyinvmanger {
            get {
                return ResourceManager.GetString("updatetostockbyinvmanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update wms.wms_stock set availableqty=availableqty+@reservedqty where itemid=@itemid.
        /// </summary>
        public static string updatetostockreserveqty {
            get {
                return ResourceManager.GetString("updatetostockreserveqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into wms.wms_transfermaterial(transferqty,createdby,createdon,remarks,projectcode,materialid)values
        ///        (@transferqty,@createdby,current_timestamp,@remarks,@projectcode,@materialid) RETURNING transferid.
        /// </summary>
        public static string updatetransferdata {
            get {
                return ResourceManager.GetString("updatetransferdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select stinw.inwmasterid as value,stinw.inwardid as text,stk.itemlocation as supplier from wms.wms_storeinward stinw 
        ///left outer join wms.wms_stock stk on stk.inwardid = stinw.inwardid
        ///where stk.itemlocation is NULL and stinw.inwmasterid = &apos;#inwmasterid&apos;.
        /// </summary>
        public static string validategrnlistfornotify {
            get {
                return ResourceManager.GetString("validategrnlistfornotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select grnnumber from wms.wms_securityinward inw 
        ///inner join wms.wms_polist openpo on inw.pono=openpo.pono 
        ///where  inw.invoiceno=&apos;#invoiceno&apos; and openpo.pono=&apos;#pono&apos;.
        /// </summary>
        public static string verifyGRNgenerated {
            get {
                return ResourceManager.GetString("verifyGRNgenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Count(*),grnnumber from wms.wms_securityinward inw 
        ///inner join wms.wms_polist openpo on inw.pono=openpo.pono 
        ///where  inw.invoiceno=&apos;#invoiceno&apos; and openpo.pono=&apos;#pono&apos; group by grnnumber.
        /// </summary>
        public static string Verifythreewaymatch {
            get {
                return ResourceManager.GetString("Verifythreewaymatch", resourceCulture);
            }
        }
    }
}
